name = "PackageStyle"
uuid = "8f8e8b97-76cc-4caf-a6ff-c914906f2a3c"
authors = ["Emmanuel Sales <absolutezero2a03@gmail.com>"]
version = "0.1.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"

[compat]
julia = "1.6"
